sincronizar_a_github:
  image: alpine:latest
  before_script:
    - apk add --no-cache git openssh-client
  script:
    - git remote add github https://x-access-token:${GITHUB_TOKEN}@github.com/nullMarcos/proyecto-redes.git || true
    - git fetch github main
    - if [ "$(git rev-parse HEAD)" = "$(git rev-parse github/main)" ]; then echo "Repositorios idénticos. Todo al día."; else git push github main; fi
