name: "redes-de-computadores"

services:
  torre:
    build:
      context: "./torre/"
      dockerfile: "./dockerfile"

    image: "torre"
    container_name: "torre"

    environment:
      - TORRE_ID=1

    depends_on:
      servidor:
        condition: service_healthy
        restart: true

    volumes:
      - type: bind
        source: "./torre/"
        target: "/service/"

  servidor:
    build:
      context: "."
      dockerfile: "./servidor/dockerfile"

    image: "servidor"
    container_name: "servidor"

    environment:
      - DATABASE_URL=sqlite:////data/monitoreo_industrial.db

    ports:
      - 5050:5050

    volumes:
      - ./servidor:/app/servidor
      - ./database:/app/database
      - ./alembic.ini:/app/alembic.ini
      - ./data:/data
