"""Make id_operador not nullable in Comando

Revision ID: 1253a9d58d1d
Revises: 6a7f89bf5672
Create Date: 2026-07-04 16:48:02.192293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1253a9d58d1d'
down_revision: Union[str, Sequence[str], None] = '6a7f89bf5672'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Asegurar que el operador 0 existe para evitar violar la Foreign Key
    conn = op.get_bind()
    conn.execute(
        sa.text(
            "INSERT OR IGNORE INTO operador (id, nombre, email, password_hash) "
            "VALUES (0, 'Sistema Central (Automático)', 'sistema.central@empresa.com', 'pbkdf2:sha256:600000$system$default_password_hash')"
        )
    )

    # 2. Actualizar los comandos automáticos existentes con id_operador NULL a 0
    conn.execute(
        sa.text("UPDATE comando SET id_operador = 0 WHERE id_operador IS NULL")
    )

    # 3. Aplicar la restricción NOT NULL
    with op.batch_alter_table('comando') as batch_op:
        batch_op.alter_column('id_operador',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comando') as batch_op:
        batch_op.alter_column('id_operador',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
