"""Initial migration

Revision ID: 6a7f89bf5672
Revises: 
Create Date: 2026-07-04 13:48:39.119721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a7f89bf5672'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('torre_blanqueamiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=False),
    sa.Column('creada_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerta_proceso',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_torre', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tipo_alerta', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_torre'], ['torre_blanqueamiento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerta_seguridad',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_torre', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tipo_evento', sa.String(length=100), nullable=False),
    sa.Column('origen_ip', sa.String(length=45), nullable=True),
    sa.Column('payload_sospechoso', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_torre'], ['torre_blanqueamiento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comando',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_torre', sa.Integer(), nullable=False),
    sa.Column('id_operador', sa.Integer(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tipo_instruccion', sa.String(length=100), nullable=False),
    sa.Column('valor_parametro', sa.Float(), nullable=True),
    sa.Column('estado_ejecucion', sa.String(length=50), nullable=False),
    sa.Column('hash_comando', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_operador'], ['operador.id'], ),
    sa.ForeignKeyConstraint(['id_torre'], ['torre_blanqueamiento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reporte_telemetria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_torre', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('nivel', sa.Float(), nullable=True),
    sa.Column('flujo_pulpa', sa.Float(), nullable=True),
    sa.Column('flujo_clo2', sa.Float(), nullable=True),
    sa.Column('caudal_total', sa.Float(), nullable=True),
    sa.Column('temperatura', sa.Float(), nullable=True),
    sa.Column('ph', sa.Float(), nullable=True),
    sa.Column('presion', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_torre'], ['torre_blanqueamiento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_torre_fecha', 'reporte_telemetria', ['id_torre', 'fecha_hora'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_torre_fecha', table_name='reporte_telemetria')
    op.drop_table('reporte_telemetria')
    op.drop_table('comando')
    op.drop_table('alerta_seguridad')
    op.drop_table('alerta_proceso')
    op.drop_table('torre_blanqueamiento')
    op.drop_table('operador')
    # ### end Alembic commands ###
