FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

# Actualizar el sistema e instalar Python 3, pip y dependencias necesarias
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    && rm -rf /var/lib/apt/lists/*

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos de la carpeta del servidor al contenedor
COPY . /app/server

#  Instalar las librerías de Python requeridas para el servidor
RUN pip3 install --break-system-packages fastapi uvicorn websockets
EXPOSE 5050
CMD ["python3", "server/server.py"]