FROM ubuntu:24.04
	ENV DEBIAN_FRONTEND=noninteractive
	ENV TOKEN_SECRETO="celulosa_secure_2026"
	
	HEALTHCHECK --interval=5s --timeout=5s --start-period=5s --retries=5 \
		CMD curl --fail --insecure "https://0.0.0.0:5050/" || exit 1
	
	# Actualizar el sistema e instalar Python 3, pip y dependencias necesarias
	RUN apt-get update && apt-get install -y \
		python3 \
		python3-pip \
		python3-venv \
		curl \
		&& rm -rf /var/lib/apt/lists/*
	
	# Establecer el directorio de trabajo dentro del contenedor
	WORKDIR /app
	
	# Copiar las carpetas necesarias al contenedor
	COPY ./database /app/database
	COPY ./servidor /app/servidor
	COPY ./alembic.ini /app/alembic.ini
	
	# Instalar las librerías de Python requeridas para el servidor 
	RUN pip3 install --break-system-packages fastapi uvicorn websockets sqlalchemy alembic pyjwt Werkzeug python-multipart
	EXPOSE 5050
	CMD ["sh", "-c", "alembic upgrade head && python3 servidor/server.py"]