FROM python:3.14
	
	EXPOSE 5050
	WORKDIR /service/
	
	ARG DEBIAN_FRONTEND=noninteractive
	
	HEALTHCHECK --interval=5s --timeout=5s --start-period=5s --retries=5 \
		CMD curl --fail --insecure "https://0.0.0.0:5050/" || exit 1
	
	COPY ./requirements.txt ./
	
	RUN python3 -m pip install --upgrade pip && \
		python3 -m pip install --requirement requirements.txt
	
	COPY ./ ./
	
	ENTRYPOINT ["./run.sh"]